version: 2

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w"

      - -X github.com/JenspederM/pybundler/internal/build.buildProjectName={{ .ProjectName }}
      - -X github.com/JenspederM/pybundler/internal/build.buildVersion={{ .Version }}

      # Git information
      - -X github.com/JenspederM/pybundler/internal/build.buildBranch={{ .Branch }}
      - -X github.com/JenspederM/pybundler/internal/build.buildTag={{ .Tag }}
      - -X github.com/JenspederM/pybundler/internal/build.buildShortCommit={{ .ShortCommit }}
      - -X github.com/JenspederM/pybundler/internal/build.buildFullCommit={{ .FullCommit }}
      - -X github.com/JenspederM/pybundler/internal/build.buildCommitTimestamp={{ .CommitTimestamp }}
      - -X github.com/JenspederM/pybundler/internal/build.buildSummary={{ .Summary }}

      # Version information
      - -X github.com/JenspederM/pybundler/internal/build.buildMajor={{ .Major }}
      - -X github.com/JenspederM/pybundler/internal/build.buildMinor={{ .Minor }}
      - -X github.com/JenspederM/pybundler/internal/build.buildPatch={{ .Patch }}
      - -X github.com/JenspederM/pybundler/internal/build.buildPrerelease={{ .Prerelease }}
      - -X github.com/JenspederM/pybundler/internal/build.buildIsSnapshot={{ .IsSnapshot }}
      - -X github.com/JenspederM/pybundler/internal/build.buildTimestamp={{ .Timestamp }}

    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: pybundler

archives:
  - formats: ["zip", "tar.gz"]

    # Include version in archive only for release builds and not for snapshot builds.
    # Snapshot archives must have a stable file name such that the artifacts in the nightly
    # release are automatically overwritten. If the snapshot version is included in the
    # file name then additional logic to clean up older builds would be needed.
    name_template: "pybundler_cli_{{ if not .IsSnapshot }}{{ .Version }}_{{ end }}{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "pybundler_cli_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-dev+{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
