# Build the application from source
FROM golang:1.23 AS build-stage
WORKDIR /app
COPY . ./
RUN go mod vendor
RUN CGO_ENABLED=0 GOOS=linux go build -o /{{ .AppName }}

# Deploy the application binary into a lean image
FROM gcr.io/distroless/python3-debian12 AS build-release-stage
WORKDIR /
COPY --from=build-stage /{{ .AppName }} /{{ .AppName }}
EXPOSE 8080
ENTRYPOINT ["/{{ .AppName }}"]